version: '3.7'

services:
  api:
    # Uncomment for live-reload in development:
    command: ['/start-reload.sh']

    build: ./api
    image: tgfeed:0.1.0
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - 1337:80
    volumes:
      - ./api:/app
    depends_on:
      - db
      - storage
      - proxy
  db:
    image: mongo:4.2.1
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./db:/data/db
  storage:
    image: minio/minio:RELEASE.2020-01-16T22-40-29Z
    restart: unless-stopped
    env_file:
      - .env
    command: server /data/storage
    volumes:
      - ./storage:/data/storage
  proxy:
    image: dperson/torproxy
    restart: unless-stopped
