[telegram]
api_id = 'YOUR_API_ID'
api_hash = 'YOUR_API_HASH'
phone = 'YOUR_PHONE'
channels = ['YOUR_CHANNEL']
session = 'tgfeed'
frequency = 5

[telegram.proxy]
host = 'proxy'
port = 9050

[database]
uri = 'mongodb://api:password@db:27017'
name = 'tgfeed'

[storage]
bucket = 'tgfeed'
endpoint = 'http://storage:9000'
access_key = 'access_key'
secret_key = 'secret_key'
region = 'us-east-1'
